n = input('digite algo:')
print('O tipo primitivo desse valor é {} ', type(n))
print('Só tem espaços ? ', n.isspace())
print('È um numérico? ',n.isnumeric())
print('È alfabético? ',n.isalpha())
print('È alfanumérico? ',n.isalnum())
print('Está em maiúsculo? ',n.isupper())
print('Está em minúsculo? ',n.islower())
print('Está capitalizado? ',n.istitle())
